# <auto-generated description="read C# config models -> generate C# Controller + TS types/API" />
param(
    [string]$ProjectRoot = $PSScriptRoot
)

$ErrorActionPreference = "Stop"

$modelsDir   = Join-Path $ProjectRoot "JiaoLongControl\Server\Core\Models"
$outputCs    = Join-Path $ProjectRoot "JiaoLongControl\Server\Core\Controllers\ConfigController.Generated.cs"
$outputTs    = Join-Path $ProjectRoot "JiaoLongControl\Client\src\utils\bridge.config.gen.ts"

# ── Parse helpers ──────────────────────────────────────────────

function Parse-Class($filePath) {
    $text = Get-Content $filePath -Raw

    # class that extends PageConfigBase
    $cfgMatch = [regex]::Match($text, 'class\s+(\w+)\s*:\s*PageConfigBase')
    if (-not $cfgMatch.Success) { return $null }

    $className = $cfgMatch.Groups[1].Value
    $cfgStart  = $cfgMatch.Index

    # opening brace of the config class
    $bracePos = $text.IndexOf('{', $cfgStart)
    if ($bracePos -lt 0) { return $null }
    $bracePos++

    # find the first nested "public class" AFTER the config class
    $nestedStartPos = $text.Length
    $allClassMatches = [regex]::Matches($text, 'public\s+class\s+(\w+)')
    foreach ($cm in $allClassMatches) {
        if ($cm.Index -gt $cfgStart -and $cm.Groups[1].Value -ne $className) {
            $nestedStartPos = $cm.Index
            break
        }
    }

    # config class body = from opening brace to first nested class (or EOF)
    $configBody = $text.Substring($bracePos, $nestedStartPos - $bracePos)

    # properties from config body only
    $props = @()
    $propRegex = [regex]::Matches($configBody, 'public\s+(\S+)\s+(\w+)\s*\{\s*get;\s*set;\s*\}\s*(?:=\s*([^;\r\n]+))?;?\s*(?:\r?\n|$)')
    foreach ($m in $propRegex) {
        $props += @{
            Type    = $m.Groups[1].Value
            Name    = $m.Groups[2].Value
            Default = if ($m.Groups[3].Success) { $m.Groups[3].Value.Trim() } else { $null }
        }
    }

    # nested classes from the text after config class body
    $nestedClasses = @()
    if ($nestedStartPos -lt $text.Length) {
        $nestedText = $text.Substring($nestedStartPos)
        $nestedRegex = [regex]::Matches($nestedText, '(?s)public\s+class\s+(\w+)\s*(?::\s*\w+)?\s*\{(.+?)\n\s*\}')
        foreach ($nm in $nestedRegex) {
            $nestedName = $nm.Groups[1].Value
            $nestedBody = $nm.Groups[2].Value
            $nestedProps = @()
            $npRegex = [regex]::Matches($nestedBody, 'public\s+(\S+)\s+(\w+)\s*\{\s*get;\s*set;\s*\}')
            foreach ($npm in $npRegex) {
                $nestedProps += @{
                    Type = $npm.Groups[1].Value
                    Name = $npm.Groups[2].Value
                }
            }
            $nestedClasses += @{
                Name       = $nestedName
                Properties = $nestedProps
            }
        }
    }

    return @{
        ClassName      = $className
        Properties     = $props
        NestedClasses  = $nestedClasses
    }
}

function CSharp-ToTS($csType) {
    switch -Regex ($csType) {
        '^bool$'              { return 'boolean' }
        '^byte$|^int$|^uint$|^short$|^ushort$|^long$|^ulong$|^float$|^double$|^decimal$' { return 'number' }
        '^string$'            { return 'string' }
        '^List<(.+)>$'        { return (CSharp-ToTS $Matches[1]) + '[]' }
        default               { return $csType }      # custom nested type
    }
}

# ── Collect all config classes ─────────────────────────────────

$configs = @()
$allNestedTypes = @{}    # name -> properties array (dedup)

Get-ChildItem $modelsDir -Filter "*PageConfig.cs" | ForEach-Object {
    $parsed = Parse-Class $_.FullName
    if ($parsed) {
        # derive file key: AppPageConfig -> "app.json"
        $key = $parsed.ClassName -replace 'PageConfig$',''
        $fileName = "$($key.ToLower()).json"
        # derive bridge property name: AppPageConfig -> AppConfig
        $bridgeProp = $parsed.ClassName -replace 'Page(?=Config)',''

        $configs += @{
            ClassName   = $parsed.ClassName
            Key         = $key          # e.g. "App", "Cpu", "Fan", "Gpu", "Smu"
            FileName    = $fileName     # e.g. "app.json"
            BridgeProp  = $bridgeProp   # e.g. "AppConfig", "CpuConfig"
            MethodName  = "${key}Config" # e.g. "AppConfig", "CpuConfig"
            Properties  = $parsed.Properties
            NestedClasses = $parsed.NestedClasses
        }

        foreach ($nc in $parsed.NestedClasses) {
            if (-not $allNestedTypes.ContainsKey($nc.Name)) {
                $allNestedTypes[$nc.Name] = $nc.Properties
            }
        }
    }
}

# sort for stable output
$configs = $configs | Sort-Object Key

Write-Host "Found $($configs.Count) config classes: $($configs.Key -join ', ')"
Write-Host "Found $($allNestedTypes.Count) nested types: $($allNestedTypes.Keys -join ', ')"

# ── Generate C# partial class ──────────────────────────────────

$csHeader = @'
// <auto-generated>
// This file is auto-generated by generate-config.ps1
// Manual changes will be overwritten.
// Source of truth: Server/Core/Models/*PageConfig.cs
// </auto-generated>

using System;
using JiaoLongControl.Server.Core.Models;
using JiaoLongControl.Server.Core.Utils;
using JiaoLongControl.Server.Interop;

namespace JiaoLongControl.Server.Core.Controllers;

public partial class ConfigController
{
'@

$csBody = ""
foreach ($cfg in $configs) {
    $csBody += @"

    public CommandResult Get$($cfg.MethodName)()
    {
        try { return new CommandResult(true, $('"成功"'), Bridge.Instance.$($cfg.BridgeProp)); }
        catch (Exception ex) { return new CommandResult(false, ex.Message); }
    }

    public CommandResult Set$($cfg.MethodName)($($cfg.ClassName) config)
    {
        try
        {
            config.Save($('"' + $cfg.FileName + '"'));
            Bridge.Instance.$($cfg.BridgeProp) = config;
            return new CommandResult(true, $('"保存成功"'));
        }
        catch (Exception ex) { return new CommandResult(false, ex.Message); }
    }
"@
}

$csFooter = "`n}"

$csOutput = $csHeader + $csBody + $csFooter
Set-Content -Path $outputCs -Value $csOutput -Encoding UTF8
Write-Host "Generated: $outputCs"

# ── Generate TypeScript types + API ────────────────────────────

$tsLines = @()
$tsLines += '// <auto-generated>'
$tsLines += '// This file is auto-generated by generate-config.ps1'
$tsLines += '// Manual changes will be overwritten.'
$tsLines += '// Source of truth: Server/Core/Models/*PageConfig.cs'
$tsLines += '// </auto-generated>'
$tsLines += ''
$tsLines += "import { call, raw, type CommandResult } from './bridge';"
$tsLines += ''

# nested type interfaces first
foreach ($kv in $allNestedTypes.GetEnumerator() | Sort-Object Key) {
    $tsLines += "export interface $($kv.Key) {"
    foreach ($p in $kv.Value) {
        $tsType = CSharp-ToTS $p.Type
        $tsLines += "    $($p.Name): $tsType;"
    }
    $tsLines += '}'
    $tsLines += ''
}

# config type interfaces
foreach ($cfg in $configs) {
    $typeName = "$($cfg.Key)ConfigType"
    $tsLines += "export interface $typeName {"
    foreach ($p in $cfg.Properties) {
        $tsType = CSharp-ToTS $p.Type
        $tsLines += "    $($p.Name): $tsType;"
    }
    $tsLines += '}'
    $tsLines += ''
}

# API wrapper
$tsLines += 'export const Config = {'
foreach ($cfg in $configs) {
    $typeName = "$($cfg.Key)ConfigType"
    $tsLines += "    Get$($cfg.MethodName): () => call<$typeName>(raw.Config.Get$($cfg.MethodName)()),"
    $tsLines += "    Set$($cfg.MethodName): (config: $typeName) => call(raw.Config.Set$($cfg.MethodName)(config)),"
}
$tsLines += '};'

$tsOutput = ($tsLines -join "`n") + "`n"
Set-Content -Path $outputTs -Value $tsOutput -Encoding UTF8
Write-Host "Generated: $outputTs"
Write-Host "Done."
