<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <RootNamespace>test</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\JiaoLongControl\JiaoLongControl.csproj" />
    </ItemGroup>
    <ItemGroup>
        <None Update="AMDFamily17.bin">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>Drivers\PawnIO\AMDFamily17.bin</TargetPath>
        </None>
    </ItemGroup>
</Project>