// <auto-generated>
// This file is auto-generated by generate-config.ps1
// Manual changes will be overwritten.
// Source of truth: Server/Core/Models/*PageConfig.cs
// </auto-generated>

import { call, raw, type CommandResult } from './bridge';

export interface CpuProfilePreset {
    CpuLongPower: number;
    CpuShortPower: number;
    CpuTempWall: number;
    CpuMaxFrequency: number;
    CpuTurbo: boolean;
}

export interface FanPoint {
    temp: number;
    speed: number;
}

export interface GpuConfigType {
    GpuClock: number;
    MemoryClock: number;
    PowerLimit: number;
}

export interface SmuConfigType {
    StapmLimit: number;
    StapmTime: number;
    FastLimit: number;
    SlowLimit: number;
    SlowTime: number;
    PptLimitRsmu: number;
    VrmCurrentMp1: number;
    VrmCurrentRsmu: number;
    TdcLimitMp1: number;
    TdcLimitRsmu: number;
    EdcLimitMp1: number;
    EdcLimitRsmu: number;
    TempLimitMp1: number;
    TempLimitRsmu: number;
    PboScalar: number;
    OcClk: number;
    OcVolt: number;
    CurveOptimizerAll: number;
}

export interface FanConfigType {
    FanCurveMerge: boolean;
    ManualFanSpeed: number;
    CpuFanCurve: FanPoint[];
    GpuFanCurve: FanPoint[];
}

export interface AppConfigType {
    BootMinimized: boolean;
    BootAdvancedFanControlSystem: boolean;
    BootAdvancedCPUSystem: boolean;
    BootAdvancedGPUSystem: boolean;
    BootSetRyzenSumCurveOptimizerAll: boolean;
}

export interface CpuConfigType {
    CpuLongPower: number;
    CpuShortPower: number;
    CpuTempWall: number;
    CpuMaxFrequency: number;
    CpuTurbo: boolean;
    DefaultProfile: CpuProfilePreset;
    PerformanceProfile: CpuProfilePreset;
    SavingProfile: CpuProfilePreset;
    CustomProfile: CpuProfilePreset;
}

export const Config = {
    GetGpuConfig: () => call<GpuConfigType>(raw.Config.GetGpuConfig()),
    SetGpuConfig: (config: GpuConfigType) => call(raw.Config.SetGpuConfig(config)),
    GetSmuConfig: () => call<SmuConfigType>(raw.Config.GetSmuConfig()),
    SetSmuConfig: (config: SmuConfigType) => call(raw.Config.SetSmuConfig(config)),
    GetFanConfig: () => call<FanConfigType>(raw.Config.GetFanConfig()),
    SetFanConfig: (config: FanConfigType) => call(raw.Config.SetFanConfig(config)),
    GetAppConfig: () => call<AppConfigType>(raw.Config.GetAppConfig()),
    SetAppConfig: (config: AppConfigType) => call(raw.Config.SetAppConfig(config)),
    GetCpuConfig: () => call<CpuConfigType>(raw.Config.GetCpuConfig()),
    SetCpuConfig: (config: CpuConfigType) => call(raw.Config.SetCpuConfig(config)),
};

