<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <RootNamespace>JiaoLongControl_Test</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\JiaoLongControl\JiaoLongControl.csproj" />
    </ItemGroup>
</Project>
